---
apiVersion: tunnel/v1
kind: Deployment
metadata:
  name: go-http-tunnel-deploy
spec:
  containers:
    - name: go-http-tunnel
      image: docker.io/mydock408/tunnel-release:latest
      ports:
        - containerPort: 5223
