apiVersion: v1
kind: Deployment
metadata:
  name: tunnel-deployment
spec:
  selector:
    matchLabels:
      app: go-tunnel
  replicas: 1
  template:
    metadata:
      labels:
        app: go-tunnel
    spec:
      containers:
      - name: go-http-tunnel
        image: docker.io/mydock408/tunnel-release:latest
        ports:
        - containerPort: 5223
