  
apiVersion: v1
kind: Pod
metadata:
  name: tunneldeployment
spec:
  containers:
      - name: gohttptunnel
        image: docker.io/mydock408/tunnel-release:latest
        ports:
        - containerPort: 5223
